spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sistemafestival?serverTimezone=America/Argentina/Buenos_Aires}
    username: ${USERNAME:root}
    password: ${PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
